name: geotrack24fsc
description: "A new Flutter project."

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.9.01+16

environment:
  sdk: '>=3.2.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  flutter_svg:
  google_fonts: ^6.2.1
  get: ^4.6.5
  fluttertoast:
  connectivity_plus:
  get_storage:
  alice: ^1.0.0-dev.12
  alice_dio: ^1.0.4
#  alice: ^0.4.2
#  flutter_alice: ^2.0.1

  dio:

  package_info_plus:
  cached_network_image:
  flutter_native_splash:
  intl:
  slider_button: ^2.1.0
  timeline_tile:
  fl_chart: ^1.0.0

#  workmanager: ^0.5.2
#  workmanager:
#  geolocator: 13.0.4
#  geolocator_android: ^5.0.1+1
  geolocator_android: ^5.0.2
  geolocator: ^14.0.2
#  geolocator: ^14.0.0
  geolocator_web:
  flutter_local_notifications:
  firebase_core:
  disable_battery_optimization: 1.1.1
  firebase_crashlytics:
  firebase_messaging:
  permission_handler:
  #background_locator_2: ^2.0.6
  #flutter_background_geolocation: '^4.12.0'
  flutter_background_service: any
  flutter_background_service_android: ^6.3.0
  url_launcher:
  flutter_inappwebview: ^6.0.0




#  image_picker:
  mat_month_picker_dialog:
  google_maps_flutter:
  just_audio:
  record:
  path_provider:
  flutter_polyline_points: ^3.0.1
# flutter_foreground_task: ^6.5.0
  flutter_overlay_window: ^0.5.0
  device_info_plus: ^11.5.0

  app_settings: ^6.1.1
  in_app_update: ^4.2.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons:
  change_app_package_name: ^1.0.0


flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  remove_alpha_ios: true
  image_path: "assets/logo/24FSC.png"

flutter_native_splash:
  android: true
  ios: true
  web: false
  color: "#FFFFFF"
  color_dark: "#FFFFFF"
  image: "assets/logo/24FSC.png"
  android_12:
    image: "assets/logo/24FSC.png"


flutter:

  uses-material-design: true
  assets:
    - assets/
    - assets/onboarding/
    - assets/icons/
    - assets/topbar/
    - assets/logo/
    - assets/menu/
    - assets/circular/


